
[build-dependencies]

  [build-dependencies.tauri-build]
    features = []
    version = "1.3"

[dependencies]
  serde_json = "1.0"

  [dependencies.reqwest]
    features = ["json", "blocking"]
    version = "0.11"

  [dependencies.serde]
    features = ["derive"]
    version = "1.0"

  [dependencies.tauri]
    features = [ "shell-sidecar", "updater", "system-tray", "process-exit", "dialog-all", "path-all", "process-command-api"]
    version = "1.3"
  
  [dependencies.fix-path-env]
    git = "https://github.com/tauri-apps/fix-path-env-rs"
    branch = "dev"

[features]
  custom-protocol = ["tauri/custom-protocol"]

[package]
  authors = ["you"]
  description = "A Tauri App"
  edition = "2021"
  license = ""
  name = "prem-app"
  repository = ""
  version = "0.0.32"
