name: Format and build

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Sync node version and setup cache
        uses: actions/setup-node@v3

      - name: Install frontend dependencies
        run: npm install
      
      - name: Run prettier
        run: npm run prettier:check

      - name: Build frontend
        run: npm run build